apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadwatf5493-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadwatf5493-tenant-component
    app.kubernetes.io/part-of: loadwatf5493-tenant-app
  name: loadwatf5493-tenant-component
  namespace: loadwatf5493-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadwatf5493-tenant-component
    weight: null
status: {}
